{{ $fullname := include "sentiment.fullname" . }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "sentiment.labels" . | nindent 4 }}
spec:
  tls:
  - hosts:
    {{ toYaml .Values.hostnames | nindent 4 }}
    {{- if .Values.tls.secret }}
    secretName: {{ .Values.tls.secret }}
    {{- else }}
    secretName: "{{ $fullname }}-cert"
    {{- end }}
  rules:
  {{- range .Values.hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullname }}
          servicePort: {{ $.Values.port }}
  {{- end }}
