{{ $fullname := include "sentiment.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "sentiment.labels" . | nindent 4 }}
data:
  MODEL_TOKEN: {{ .Values.token | b64enc | quote }}
