{{ $fullname := include "sentiment.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "sentiment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sentiment.selectorLabels" . | nindent 4 }}
  ports:
  - name: www
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}

