replication:
    initialCount: 1
    strategyType: RollingUpdate

image:
    repository: warpcomdev/sentiment
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

#livenessProbe:
#    initialDelaySeconds: 300
#    periodSeconds: 30
#    timeoutSeconds: 5
#    successThreshold: 1
#    failureThreshold: 3

resources:
    limits:
        cpu: "4"
        memory: "4Gi"
    requests:
        cpu: "500m"
        memory: "2Gi"

# Hostname for the Kubernetes ingress 
hostname: "sentiment.<your-wildcard-DNS>"
# Path to folder containing .env file (if any)
env_dir: "/etc/sentiment"
# Path to volume storing model cache
cache_dir: "/var/cache/sentiment"
# Name of hugginface hub's model
model: "nlptown/bert-base-multilingual-uncased-sentiment"
# True if model is stored in pytorch format as opposed to tensorflow.
isPyTorch: true
# TCP port to listen on
port: 3000
# Bearer token for protected queries
token: "ThisIsYourBearerTokenKeepItSecret"

