{{- $fullname := include "login.fullname" . }}
{{- $servicePort := .Values.port }}
{{- range $provider, $domains := .Values.hostnames }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullname }}-{{ $provider }}"
  labels:
    {{- include "login.labels" $ | nindent 4 }}
spec:
  tls:
  - hosts:
    {{ toYaml $domains | nindent 4 }}
    {{- if $.Values.tls.secret }}
    secretName: {{ $.Values.tls.secret }}
    {{- else }}
    secretName: "{{ $fullname }}-{{ $provider }}-cert"
    {{- end }}
  rules:
  {{- range $domains }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ $fullname }}-{{ $provider }}"
          servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
