{{ $fullname := include "login.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-youtube
  labels:
    {{- include "login.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.youtube.secretKey | b64enc | quote }}
  client_secret.json: {{ .Values.youtube.clientSecret | b64enc | quote }}