{{ $fullname := include "sentiment.fullname" . }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "sentiment.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullname }}
          servicePort: {{ .Values.port }}
